### PR TITLE
Orderitemtest

### PR DESCRIPTION
**Pull request by amosfong**

### CODE REVIEW

**Comment by riccardo-alberti** [comment]
@amosfong why the custom field change was done to modules outside of commerce also?

**Comment by amosfong** [comment]
@riccardo-alberti, headless-delivery had EntityFieldsUtil which already does what we needed but it was internal. So I pulled it out into the common-spi module so it can be used in other modules like the commerce one.

**Comment by amosfong** [comment]
@riccardo-alberti, is it ok? Does anything need to change?

**Comment by riccardo-alberti** [comment]
@amosfong please see https://issues.liferay.com/browse/COMMERCE-9135 thanks

**Comment by amosfong** [comment]
got it, thanks!

**Pull request closed without merging**
